<script lang="ts">
  interface EmojiItem {
    emoji: string;
    desc: string;
  }

  interface EmojiCategory {
    name: string;
    emojis: EmojiItem[];
  }

  const emojiCategories: EmojiCategory[] = [
    {
      name: "Smileys & Emotion",
      emojis: [
        { emoji: "😀", desc: "grinning face" }, { emoji: "😃", desc: "grinning face big eyes" }, { emoji: "😄", desc: "grinning face smiling eyes" }, { emoji: "😁", desc: "beaming face" }, { emoji: "😆", desc: "grinning squinting face" }, { emoji: "😅", desc: "grinning face sweat" }, { emoji: "🤣", desc: "rolling floor laughing" }, { emoji: "😂", desc: "face tears joy" }, { emoji: "🙂", desc: "slightly smiling face" }, { emoji: "🙃", desc: "upside down face" }, { emoji: "😉", desc: "winking face" }, { emoji: "😊", desc: "smiling face smiling eyes" }, { emoji: "😇", desc: "smiling face halo angel" }, { emoji: "🥰", desc: "smiling face hearts love" }, { emoji: "😍", desc: "smiling face heart eyes" }, { emoji: "🤩", desc: "star struck excited" }, { emoji: "😘", desc: "face blowing kiss" }, { emoji: "😗", desc: "kissing face" }, { emoji: "☺️", desc: "smiling face" }, { emoji: "😚", desc: "kissing face closed eyes" }, { emoji: "😙", desc: "kissing face smiling eyes" }, { emoji: "🥲", desc: "smiling face tear" },
        { emoji: "😋", desc: "face savoring food yummy" }, { emoji: "😛", desc: "face tongue" }, { emoji: "😜", desc: "winking face tongue" }, { emoji: "🤪", desc: "zany face crazy" }, { emoji: "😝", desc: "squinting face tongue" }, { emoji: "🤑", desc: "money mouth face rich" }, { emoji: "🤗", desc: "hugging face" }, { emoji: "🤭", desc: "face hand over mouth" }, { emoji: "🤫", desc: "shushing face quiet" }, { emoji: "🤔", desc: "thinking face" }, { emoji: "🤐", desc: "zipper mouth face" }, { emoji: "🤨", desc: "face raised eyebrow" }, { emoji: "😐", desc: "neutral face" }, { emoji: "😑", desc: "expressionless face" }, { emoji: "😶", desc: "face without mouth" }, { emoji: "😏", desc: "smirking face" }, { emoji: "😒", desc: "unamused face" }, { emoji: "🙄", desc: "face rolling eyes" }, { emoji: "😬", desc: "grimacing face" }, { emoji: "🤥", desc: "lying face pinocchio" }, { emoji: "😌", desc: "relieved face" }, { emoji: "😔", desc: "pensive face sad" },
        { emoji: "😪", desc: "sleepy face" }, { emoji: "🤤", desc: "drooling face" }, { emoji: "😴", desc: "sleeping face zzz" }, { emoji: "😷", desc: "face medical mask sick" }, { emoji: "🤒", desc: "face thermometer fever" }, { emoji: "🤕", desc: "face head bandage hurt" }, { emoji: "🤢", desc: "nauseated face sick" }, { emoji: "🤮", desc: "face vomiting throw up" }, { emoji: "🤧", desc: "sneezing face" }, { emoji: "🥵", desc: "hot face sweating" }, { emoji: "🥶", desc: "cold face freezing" }, { emoji: "🥴", desc: "woozy face drunk" }, { emoji: "😵", desc: "dizzy face" }, { emoji: "🤯", desc: "exploding head mind blown" }, { emoji: "🤠", desc: "cowboy hat face" }, { emoji: "🥳", desc: "partying face celebration" }, { emoji: "🥸", desc: "disguised face" }, { emoji: "😎", desc: "smiling face sunglasses cool" }, { emoji: "🤓", desc: "nerd face glasses" }, { emoji: "🧐", desc: "face monocle" }, { emoji: "😕", desc: "confused face" }, { emoji: "😟", desc: "worried face" },
        { emoji: "🙁", desc: "slightly frowning face" }, { emoji: "☹️", desc: "frowning face" }, { emoji: "😮", desc: "face open mouth" }, { emoji: "😯", desc: "hushed face" }, { emoji: "😲", desc: "astonished face" }, { emoji: "😳", desc: "flushed face embarrassed" }, { emoji: "🥺", desc: "pleading face puppy eyes" }, { emoji: "😦", desc: "frowning face open mouth" }, { emoji: "😧", desc: "anguished face" }, { emoji: "😨", desc: "fearful face" }, { emoji: "😰", desc: "anxious face sweat" }, { emoji: "😥", desc: "sad but relieved face" }, { emoji: "😢", desc: "crying face" }, { emoji: "😭", desc: "loudly crying face" }, { emoji: "😱", desc: "face screaming fear" }, { emoji: "😖", desc: "confounded face" }, { emoji: "😣", desc: "persevering face" }, { emoji: "😞", desc: "disappointed face" }, { emoji: "😓", desc: "downcast face sweat" }, { emoji: "😩", desc: "weary face" }, { emoji: "😫", desc: "tired face" }, { emoji: "🥱", desc: "yawning face" },
        { emoji: "😤", desc: "face steam nose angry" }, { emoji: "😡", desc: "pouting face angry" }, { emoji: "😠", desc: "angry face" }, { emoji: "🤬", desc: "face symbols mouth swearing" }, { emoji: "😈", desc: "smiling face horns devil" }, { emoji: "👿", desc: "angry face horns devil" }, { emoji: "💀", desc: "skull dead" }, { emoji: "☠️", desc: "skull crossbones death" }, { emoji: "💩", desc: "pile poo poop" }, { emoji: "🤡", desc: "clown face" }, { emoji: "👹", desc: "ogre monster" }, { emoji: "👺", desc: "goblin monster" }, { emoji: "👻", desc: "ghost" }, { emoji: "👽", desc: "alien" }, { emoji: "👾", desc: "alien monster space invader" }, { emoji: "🤖", desc: "robot face" }, { emoji: "😺", desc: "grinning cat" }, { emoji: "😸", desc: "grinning cat smiling eyes" }, { emoji: "😹", desc: "cat tears joy" }, { emoji: "😻", desc: "smiling cat heart eyes" }, { emoji: "😼", desc: "cat wry smile" }, { emoji: "😽", desc: "kissing cat" },
        { emoji: "🙀", desc: "weary cat" }, { emoji: "😿", desc: "crying cat" }, { emoji: "😾", desc: "pouting cat" }, { emoji: "🙈", desc: "see no evil monkey" }, { emoji: "🙉", desc: "hear no evil monkey" }, { emoji: "🙊", desc: "speak no evil monkey" }, { emoji: "💋", desc: "kiss mark lips" }, { emoji: "💌", desc: "love letter" }, { emoji: "💘", desc: "heart arrow cupid" }, { emoji: "💝", desc: "heart ribbon gift" }, { emoji: "💖", desc: "sparkling heart" }, { emoji: "💗", desc: "growing heart" }, { emoji: "💓", desc: "beating heart" }, { emoji: "💞", desc: "revolving hearts" }, { emoji: "💕", desc: "two hearts" }, { emoji: "💟", desc: "heart decoration" }, { emoji: "❣️", desc: "heart exclamation" }, { emoji: "💔", desc: "broken heart" }, { emoji: "❤️‍🔥", desc: "heart fire passion" }, { emoji: "❤️‍🩹", desc: "mending heart healing" }, { emoji: "❤️", desc: "red heart love" }, { emoji: "🧡", desc: "orange heart" },
        { emoji: "💛", desc: "yellow heart" }, { emoji: "💚", desc: "green heart" }, { emoji: "💙", desc: "blue heart" }, { emoji: "💜", desc: "purple heart" }, { emoji: "🤎", desc: "brown heart" }, { emoji: "🖤", desc: "black heart" }, { emoji: "🤍", desc: "white heart" }, { emoji: "💯", desc: "hundred points perfect" }, { emoji: "💢", desc: "anger symbol" }, { emoji: "💥", desc: "collision explosion boom" }, { emoji: "💫", desc: "dizzy star" }, { emoji: "💦", desc: "sweat droplets water" }, { emoji: "💨", desc: "dashing away wind" }, { emoji: "🕳️", desc: "hole" }, { emoji: "💣", desc: "bomb" }, { emoji: "💬", desc: "speech balloon comment" }, { emoji: "👁️‍🗨️", desc: "eye speech bubble" }, { emoji: "🗨️", desc: "left speech bubble" }, { emoji: "🗯️", desc: "right anger bubble" }, { emoji: "💭", desc: "thought balloon thinking" }, { emoji: "💤", desc: "zzz sleep" }
      ],
    },
    {
      name: "People & Body",
      emojis: [
        { emoji: "👋", desc: "waving hand hello" }, { emoji: "🤚", desc: "raised back hand" }, { emoji: "🖐️", desc: "hand fingers splayed" }, { emoji: "✋", desc: "raised hand stop" }, { emoji: "🖖", desc: "vulcan salute spock" }, { emoji: "👌", desc: "ok hand" }, { emoji: "🤌", desc: "pinched fingers italian" }, { emoji: "🤏", desc: "pinching hand small" }, { emoji: "✌️", desc: "victory hand peace" }, { emoji: "🤞", desc: "crossed fingers luck" }, { emoji: "🤟", desc: "love you gesture" }, { emoji: "🤘", desc: "sign horns rock" }, { emoji: "🤙", desc: "call me hand" }, { emoji: "👈", desc: "backhand pointing left" }, { emoji: "👉", desc: "backhand pointing right" }, { emoji: "👆", desc: "backhand pointing up" }, { emoji: "🖕", desc: "middle finger" }, { emoji: "👇", desc: "backhand pointing down" }, { emoji: "☝️", desc: "index pointing up" }, { emoji: "👍", desc: "thumbs up like" }, { emoji: "👎", desc: "thumbs down dislike" }, { emoji: "✊", desc: "raised fist" },
        { emoji: "👊", desc: "oncoming fist punch" }, { emoji: "🤛", desc: "left facing fist" }, { emoji: "🤜", desc: "right facing fist" }, { emoji: "👏", desc: "clapping hands applause" }, { emoji: "🙌", desc: "raising hands celebration" }, { emoji: "👐", desc: "open hands" }, { emoji: "🤲", desc: "palms up together" }, { emoji: "🤝", desc: "handshake agreement" }, { emoji: "🙏", desc: "folded hands pray thanks" }, { emoji: "✍️", desc: "writing hand" }, { emoji: "💅", desc: "nail polish manicure" }, { emoji: "🤳", desc: "selfie" }, { emoji: "💪", desc: "flexed biceps strong muscle" }, { emoji: "🦾", desc: "mechanical arm prosthetic" }, { emoji: "🦿", desc: "mechanical leg prosthetic" }, { emoji: "🦵", desc: "leg" }, { emoji: "🦶", desc: "foot" }, { emoji: "👂", desc: "ear listen" }, { emoji: "🦻", desc: "ear hearing aid" }, { emoji: "👃", desc: "nose smell" }, { emoji: "🧠", desc: "brain mind" }, { emoji: "🫀", desc: "anatomical heart organ" },
        { emoji: "🫁", desc: "lungs breathe" }, { emoji: "🦷", desc: "tooth dental" }, { emoji: "🦴", desc: "bone skeleton" }, { emoji: "👀", desc: "eyes look" }, { emoji: "👁️", desc: "eye" }, { emoji: "👅", desc: "tongue taste" }, { emoji: "👄", desc: "mouth lips" }, { emoji: "👶", desc: "baby infant" }, { emoji: "🧒", desc: "child kid" }, { emoji: "👦", desc: "boy" }, { emoji: "👧", desc: "girl" }, { emoji: "🧑", desc: "person adult" }, { emoji: "👱", desc: "person blond hair" }, { emoji: "👨", desc: "man" }, { emoji: "🧔", desc: "man beard" }, { emoji: "👩", desc: "woman" }, { emoji: "🧓", desc: "older person elderly" }, { emoji: "👴", desc: "old man grandpa" }, { emoji: "👵", desc: "old woman grandma" }, { emoji: "🙍", desc: "person frowning" }, { emoji: "🙎", desc: "person pouting" }, { emoji: "🙅", desc: "person gesturing no" },
        { emoji: "🙆", desc: "person gesturing ok" }, { emoji: "💁", desc: "person tipping hand" }, { emoji: "🙋", desc: "person raising hand" }, { emoji: "🧏", desc: "deaf person" }, { emoji: "🙇", desc: "person bowing" }, { emoji: "🤦", desc: "person facepalming" }, { emoji: "🤷", desc: "person shrugging" }, { emoji: "👮", desc: "police officer cop" }, { emoji: "🕵️", desc: "detective spy" }, { emoji: "💂", desc: "guard" }, { emoji: "🥷", desc: "ninja" }, { emoji: "👷", desc: "construction worker" }, { emoji: "🤴", desc: "prince" }, { emoji: "👸", desc: "princess" }, { emoji: "👳", desc: "person turban" }, { emoji: "👲", desc: "person skullcap" }, { emoji: "🧕", desc: "woman headscarf hijab" }, { emoji: "🤵", desc: "person tuxedo" }, { emoji: "👰", desc: "person veil bride" }, { emoji: "🤰", desc: "pregnant woman" }, { emoji: "🤱", desc: "breast feeding" }, { emoji: "👼", desc: "baby angel cherub" },
        { emoji: "🎅", desc: "santa claus christmas" }, { emoji: "🤶", desc: "mrs claus christmas" }, { emoji: "🦸", desc: "superhero" }, { emoji: "🦹", desc: "supervillain" }, { emoji: "🧙", desc: "mage wizard" }, { emoji: "🧚", desc: "fairy" }, { emoji: "🧛", desc: "vampire" }, { emoji: "🧜", desc: "merperson mermaid" }, { emoji: "🧝", desc: "elf" }, { emoji: "🧞", desc: "genie" }, { emoji: "🧟", desc: "zombie" }, { emoji: "💆", desc: "person massage" }, { emoji: "💇", desc: "person haircut" }, { emoji: "🚶", desc: "person walking" }, { emoji: "🧍", desc: "person standing" }, { emoji: "🧎", desc: "person kneeling" }, { emoji: "🏃", desc: "person running" }, { emoji: "💃", desc: "woman dancing" }, { emoji: "🕺", desc: "man dancing" }, { emoji: "🕴️", desc: "person suit levitating" }, { emoji: "👯", desc: "people bunny ears" }, { emoji: "🧖", desc: "person sauna" },
        { emoji: "🧗", desc: "person climbing" }, { emoji: "🤸", desc: "person cartwheeling" }, { emoji: "🏌️", desc: "person golfing" }, { emoji: "🏇", desc: "horse racing" }, { emoji: "⛷️", desc: "skier skiing" }, { emoji: "🏂", desc: "snowboarder" }, { emoji: "🏋️", desc: "person lifting weights" }, { emoji: "🤼", desc: "people wrestling" }, { emoji: "🤽", desc: "person water polo" }, { emoji: "🤾", desc: "person handball" }, { emoji: "🤺", desc: "person fencing" }, { emoji: "⛹️", desc: "person bouncing ball basketball" }, { emoji: "🏊", desc: "person swimming" }, { emoji: "🚣", desc: "person rowing boat" }, { emoji: "🧘", desc: "person lotus yoga meditation" }, { emoji: "🛀", desc: "person bath" }, { emoji: "🛌", desc: "person bed sleeping" }, { emoji: "👭", desc: "women holding hands" }, { emoji: "👫", desc: "woman man holding hands couple" }, { emoji: "👬", desc: "men holding hands" }, { emoji: "💏", desc: "kiss" }, { emoji: "💑", desc: "couple heart love" },
        { emoji: "👪", desc: "family" }, { emoji: "👨‍👩‍👦", desc: "family man woman boy" }, { emoji: "👨‍👩‍👧", desc: "family man woman girl" }, { emoji: "👨‍👩‍👧‍👦", desc: "family man woman girl boy" }, { emoji: "👨‍👩‍👦‍👦", desc: "family man woman boy boy" }, { emoji: "👨‍👩‍👧‍👧", desc: "family man woman girl girl" }, { emoji: "👨‍👦", desc: "family man boy" }, { emoji: "👨‍👦‍👦", desc: "family man boy boy" }, { emoji: "👨‍👧", desc: "family man girl" }, { emoji: "👨‍👧‍👦", desc: "family man girl boy" }, { emoji: "👨‍👧‍👧", desc: "family man girl girl" }, { emoji: "👩‍👦", desc: "family woman boy" }, { emoji: "👩‍👦‍👦", desc: "family woman boy boy" }, { emoji: "👩‍👧", desc: "family woman girl" }, { emoji: "👩‍👧‍👦", desc: "family woman girl boy" }, { emoji: "👩‍👧‍👧", desc: "family woman girl girl" }, { emoji: "🗣️", desc: "speaking head talk" }, { emoji: "👤", desc: "bust silhouette person" }, { emoji: "👥", desc: "busts silhouette people" }, { emoji: "🫂", desc: "people hugging" }
      ],
    },
    {
      name: "Animals & Nature",
      emojis: [
        { emoji: "🐵", desc: "monkey face" }, { emoji: "🐒", desc: "monkey" }, { emoji: "🦍", desc: "gorilla" }, { emoji: "🦧", desc: "orangutan" }, { emoji: "🐶", desc: "dog face puppy" }, { emoji: "🐕", desc: "dog" }, { emoji: "🦮", desc: "guide dog" }, { emoji: "🐕‍🦺", desc: "service dog" }, { emoji: "🐩", desc: "poodle" }, { emoji: "🐺", desc: "wolf" }, { emoji: "🦊", desc: "fox" }, { emoji: "🦝", desc: "raccoon" }, { emoji: "🐱", desc: "cat face kitten" }, { emoji: "🐈", desc: "cat" }, { emoji: "🐈‍⬛", desc: "black cat" }, { emoji: "🦁", desc: "lion" }, { emoji: "🐯", desc: "tiger face" }, { emoji: "🐅", desc: "tiger" }, { emoji: "🐆", desc: "leopard" }, { emoji: "🐴", desc: "horse face" }, { emoji: "🐎", desc: "horse racing" }, { emoji: "🦄", desc: "unicorn" },
        { emoji: "🦓", desc: "zebra" }, { emoji: "🦌", desc: "deer" }, { emoji: "🦬", desc: "bison buffalo" }, { emoji: "🐮", desc: "cow face" }, { emoji: "🐂", desc: "ox" }, { emoji: "🐃", desc: "water buffalo" }, { emoji: "🐄", desc: "cow" }, { emoji: "🐷", desc: "pig face" }, { emoji: "🐖", desc: "pig" }, { emoji: "🐗", desc: "boar" }, { emoji: "🐽", desc: "pig nose" }, { emoji: "🐏", desc: "ram sheep" }, { emoji: "🐑", desc: "ewe sheep" }, { emoji: "🐐", desc: "goat" }, { emoji: "🐪", desc: "camel one hump" }, { emoji: "🐫", desc: "two hump camel" }, { emoji: "🦙", desc: "llama alpaca" }, { emoji: "🦒", desc: "giraffe" }, { emoji: "🐘", desc: "elephant" }, { emoji: "🦣", desc: "mammoth" }, { emoji: "🦏", desc: "rhinoceros" }, { emoji: "🦛", desc: "hippopotamus hippo" },
        { emoji: "🐭", desc: "mouse face" }, { emoji: "🐁", desc: "mouse" }, { emoji: "🐀", desc: "rat" }, { emoji: "🐹", desc: "hamster" }, { emoji: "🐰", desc: "rabbit face bunny" }, { emoji: "🐇", desc: "rabbit bunny" }, { emoji: "🐿️", desc: "chipmunk squirrel" }, { emoji: "🦫", desc: "beaver" }, { emoji: "🦔", desc: "hedgehog" }, { emoji: "🦇", desc: "bat" }, { emoji: "🐻", desc: "bear" }, { emoji: "🐻‍❄️", desc: "polar bear" }, { emoji: "🐨", desc: "koala" }, { emoji: "🐼", desc: "panda" }, { emoji: "🦥", desc: "sloth" }, { emoji: "🦦", desc: "otter" }, { emoji: "🦨", desc: "skunk" }, { emoji: "🦘", desc: "kangaroo" }, { emoji: "🦡", desc: "badger" }, { emoji: "🐾", desc: "paw prints" }, { emoji: "🦃", desc: "turkey" }, { emoji: "🐔", desc: "chicken hen" },
        { emoji: "🐓", desc: "rooster cock" }, { emoji: "🐣", desc: "hatching chick" }, { emoji: "🐤", desc: "baby chick" }, { emoji: "🐥", desc: "front facing baby chick" }, { emoji: "🐦", desc: "bird" }, { emoji: "🐧", desc: "penguin" }, { emoji: "🕊️", desc: "dove peace" }, { emoji: "🦅", desc: "eagle" }, { emoji: "🦆", desc: "duck" }, { emoji: "🦢", desc: "swan" }, { emoji: "🦉", desc: "owl" }, { emoji: "🦤", desc: "dodo" }, { emoji: "🪶", desc: "feather" }, { emoji: "🦩", desc: "flamingo" }, { emoji: "🦚", desc: "peacock" }, { emoji: "🦜", desc: "parrot" }, { emoji: "🐸", desc: "frog" }, { emoji: "🐊", desc: "crocodile alligator" }, { emoji: "🐢", desc: "turtle tortoise" }, { emoji: "🦎", desc: "lizard gecko" }, { emoji: "🐍", desc: "snake" }, { emoji: "🐲", desc: "dragon face" },
        { emoji: "🐉", desc: "dragon" }, { emoji: "🦕", desc: "sauropod dinosaur" }, { emoji: "🦖", desc: "t-rex dinosaur" }, { emoji: "🐳", desc: "spouting whale" }, { emoji: "🐋", desc: "whale" }, { emoji: "🐬", desc: "dolphin" }, { emoji: "🦭", desc: "seal" }, { emoji: "🐟", desc: "fish" }, { emoji: "🐠", desc: "tropical fish" }, { emoji: "🐡", desc: "blowfish puffer" }, { emoji: "🦈", desc: "shark" }, { emoji: "🐙", desc: "octopus" }, { emoji: "🐚", desc: "shell spiral" }, { emoji: "🐌", desc: "snail" }, { emoji: "🦋", desc: "butterfly" }, { emoji: "🐛", desc: "bug caterpillar" }, { emoji: "🐜", desc: "ant" }, { emoji: "🐝", desc: "honeybee bee" }, { emoji: "🪲", desc: "beetle" }, { emoji: "🐞", desc: "ladybug ladybird" }, { emoji: "🦗", desc: "cricket grasshopper" }, { emoji: "🪳", desc: "cockroach" },
        { emoji: "🕷️", desc: "spider" }, { emoji: "🕸️", desc: "spider web" }, { emoji: "🦂", desc: "scorpion" }, { emoji: "🦟", desc: "mosquito" }, { emoji: "🪰", desc: "fly" }, { emoji: "🪱", desc: "worm" }, { emoji: "🦠", desc: "microbe bacteria virus germ" }, { emoji: "💐", desc: "bouquet flowers" }, { emoji: "🌸", desc: "cherry blossom sakura" }, { emoji: "💮", desc: "white flower" }, { emoji: "🏵️", desc: "rosette" }, { emoji: "🌹", desc: "rose" }, { emoji: "🥀", desc: "wilted flower" }, { emoji: "🌺", desc: "hibiscus" }, { emoji: "🌻", desc: "sunflower" }, { emoji: "🌼", desc: "blossom" }, { emoji: "🌷", desc: "tulip" }, { emoji: "🌱", desc: "seedling sprout" }, { emoji: "🪴", desc: "potted plant" }, { emoji: "🌲", desc: "evergreen tree pine" }, { emoji: "🌳", desc: "deciduous tree" }, { emoji: "🌴", desc: "palm tree" },
        { emoji: "🌵", desc: "cactus" }, { emoji: "🌾", desc: "sheaf rice wheat" }, { emoji: "🌿", desc: "herb leaf" }, { emoji: "☘️", desc: "shamrock clover" }, { emoji: "🍀", desc: "four leaf clover luck" }, { emoji: "🍁", desc: "maple leaf fall autumn" }, { emoji: "🍂", desc: "fallen leaf autumn" }, { emoji: "🍃", desc: "leaf fluttering wind" }, { emoji: "🍄", desc: "mushroom" }, { emoji: "🌰", desc: "chestnut" }, { emoji: "🦀", desc: "crab" }, { emoji: "🦞", desc: "lobster" }, { emoji: "🦐", desc: "shrimp prawn" }, { emoji: "🦑", desc: "squid" }, { emoji: "🌍", desc: "globe europe africa earth" }, { emoji: "🌎", desc: "globe americas earth" }, { emoji: "🌏", desc: "globe asia australia earth" }, { emoji: "🌐", desc: "globe meridians world" }, { emoji: "🪨", desc: "rock stone" }, { emoji: "🌑", desc: "new moon" }, { emoji: "🌒", desc: "waxing crescent moon" }, { emoji: "🌓", desc: "first quarter moon" },
        { emoji: "🌔", desc: "waxing gibbous moon" }, { emoji: "🌕", desc: "full moon" }, { emoji: "🌖", desc: "waning gibbous moon" }, { emoji: "🌗", desc: "last quarter moon" }, { emoji: "🌘", desc: "waning crescent moon" }, { emoji: "🌙", desc: "crescent moon" }, { emoji: "🌚", desc: "new moon face" }, { emoji: "🌛", desc: "first quarter moon face" }, { emoji: "🌜", desc: "last quarter moon face" }, { emoji: "☀️", desc: "sun sunny" }, { emoji: "🌝", desc: "full moon face" }, { emoji: "🌞", desc: "sun face" }, { emoji: "🪐", desc: "ringed planet saturn" }, { emoji: "⭐", desc: "star" }, { emoji: "🌟", desc: "glowing star" }, { emoji: "🌠", desc: "shooting star" }, { emoji: "🌌", desc: "milky way galaxy" }, { emoji: "☁️", desc: "cloud" }, { emoji: "⛅", desc: "sun behind cloud" }, { emoji: "⛈️", desc: "cloud lightning rain storm" }, { emoji: "🌤️", desc: "sun behind small cloud" }, { emoji: "🌥️", desc: "sun behind large cloud" },
        { emoji: "🌦️", desc: "sun behind rain cloud" }, { emoji: "🌧️", desc: "cloud rain" }, { emoji: "🌨️", desc: "cloud snow" }, { emoji: "🌩️", desc: "cloud lightning" }, { emoji: "🌪️", desc: "tornado" }, { emoji: "🌫️", desc: "fog" }, { emoji: "🌬️", desc: "wind face blowing" }, { emoji: "🌀", desc: "cyclone hurricane typhoon" }, { emoji: "🌈", desc: "rainbow" }, { emoji: "🌂", desc: "closed umbrella" }, { emoji: "☂️", desc: "umbrella" }, { emoji: "☔", desc: "umbrella rain" }, { emoji: "⛱️", desc: "umbrella ground beach" }, { emoji: "⚡", desc: "high voltage lightning zap" }, { emoji: "❄️", desc: "snowflake cold winter" }, { emoji: "☃️", desc: "snowman" }, { emoji: "⛄", desc: "snowman without snow" }, { emoji: "☄️", desc: "comet" }, { emoji: "🔥", desc: "fire flame hot" }, { emoji: "💧", desc: "droplet water" }, { emoji: "🌊", desc: "water wave ocean" }
      ],
    },
    {
      name: "Food & Drink",
      emojis: [
        { emoji: "🍇", desc: "grapes" }, { emoji: "🍈", desc: "melon" }, { emoji: "🍉", desc: "watermelon" }, { emoji: "🍊", desc: "tangerine orange" }, { emoji: "🍋", desc: "lemon" }, { emoji: "🍌", desc: "banana" }, { emoji: "🍍", desc: "pineapple" }, { emoji: "🥭", desc: "mango" }, { emoji: "🍎", desc: "red apple" }, { emoji: "🍏", desc: "green apple" }, { emoji: "🍐", desc: "pear" }, { emoji: "🍑", desc: "peach" }, { emoji: "🍒", desc: "cherries" }, { emoji: "🍓", desc: "strawberry" }, { emoji: "🫐", desc: "blueberries" }, { emoji: "🥝", desc: "kiwi fruit" }, { emoji: "🍅", desc: "tomato" }, { emoji: "🫒", desc: "olive" }, { emoji: "🥥", desc: "coconut" }, { emoji: "🥑", desc: "avocado" }, { emoji: "🍆", desc: "eggplant aubergine" }, { emoji: "🥔", desc: "potato" },
        { emoji: "🥕", desc: "carrot" }, { emoji: "🌽", desc: "corn" }, { emoji: "🌶️", desc: "hot pepper chili" }, { emoji: "🫑", desc: "bell pepper" }, { emoji: "🥒", desc: "cucumber" }, { emoji: "🥬", desc: "leafy green lettuce" }, { emoji: "🥦", desc: "broccoli" }, { emoji: "🧄", desc: "garlic" }, { emoji: "🧅", desc: "onion" }, { emoji: "🍄", desc: "mushroom" }, { emoji: "🥜", desc: "peanuts" }, { emoji: "🌰", desc: "chestnut" }, { emoji: "🍞", desc: "bread" }, { emoji: "🥐", desc: "croissant" }, { emoji: "🥖", desc: "baguette bread french" }, { emoji: "🫓", desc: "flatbread" }, { emoji: "🥨", desc: "pretzel" }, { emoji: "🥯", desc: "bagel" }, { emoji: "🥞", desc: "pancakes" }, { emoji: "🧇", desc: "waffle" }, { emoji: "🧀", desc: "cheese wedge" }, { emoji: "🍖", desc: "meat bone" },
        { emoji: "🍗", desc: "poultry leg chicken" }, { emoji: "🥩", desc: "cut meat steak" }, { emoji: "🥓", desc: "bacon" }, { emoji: "🍔", desc: "hamburger burger" }, { emoji: "🍟", desc: "french fries" }, { emoji: "🍕", desc: "pizza" }, { emoji: "🌭", desc: "hot dog" }, { emoji: "🥪", desc: "sandwich" }, { emoji: "🌮", desc: "taco" }, { emoji: "🌯", desc: "burrito" }, { emoji: "🫔", desc: "tamale" }, { emoji: "🥙", desc: "stuffed flatbread pita" }, { emoji: "🧆", desc: "falafel" }, { emoji: "🥚", desc: "egg" }, { emoji: "🍳", desc: "cooking fried egg" }, { emoji: "🥘", desc: "shallow pan food paella" }, { emoji: "🍲", desc: "pot food stew" }, { emoji: "🫕", desc: "fondue" }, { emoji: "🥣", desc: "bowl spoon cereal" }, { emoji: "🥗", desc: "green salad" }, { emoji: "🍿", desc: "popcorn" }, { emoji: "🧈", desc: "butter" },
        { emoji: "🧂", desc: "salt" }, { emoji: "🥫", desc: "canned food" }, { emoji: "🍱", desc: "bento box japanese" }, { emoji: "🍘", desc: "rice cracker" }, { emoji: "🍙", desc: "rice ball onigiri" }, { emoji: "🍚", desc: "cooked rice" }, { emoji: "🍛", desc: "curry rice" }, { emoji: "🍜", desc: "steaming bowl noodles ramen" }, { emoji: "🍝", desc: "spaghetti pasta" }, { emoji: "🍠", desc: "roasted sweet potato" }, { emoji: "🍢", desc: "oden skewer" }, { emoji: "🍣", desc: "sushi" }, { emoji: "🍤", desc: "fried shrimp tempura" }, { emoji: "🍥", desc: "fish cake" }, { emoji: "🥮", desc: "moon cake" }, { emoji: "🍡", desc: "dango" }, { emoji: "🥟", desc: "dumpling" }, { emoji: "🥠", desc: "fortune cookie" }, { emoji: "🥡", desc: "takeout box chinese" }, { emoji: "🦀", desc: "crab" }, { emoji: "🦞", desc: "lobster" }, { emoji: "🦐", desc: "shrimp prawn" },
        { emoji: "🦑", desc: "squid" }, { emoji: "🦪", desc: "oyster" }, { emoji: "🍦", desc: "soft ice cream" }, { emoji: "🍧", desc: "shaved ice" }, { emoji: "🍨", desc: "ice cream" }, { emoji: "🍩", desc: "doughnut donut" }, { emoji: "🍪", desc: "cookie" }, { emoji: "🎂", desc: "birthday cake" }, { emoji: "🍰", desc: "shortcake" }, { emoji: "🧁", desc: "cupcake" }, { emoji: "🥧", desc: "pie" }, { emoji: "🍫", desc: "chocolate bar" }, { emoji: "🍬", desc: "candy" }, { emoji: "🍭", desc: "lollipop" }, { emoji: "🍮", desc: "custard pudding" }, { emoji: "🍯", desc: "honey pot" }, { emoji: "🍼", desc: "baby bottle milk" }, { emoji: "🥛", desc: "glass milk" }, { emoji: "☕", desc: "hot beverage coffee tea" }, { emoji: "🫖", desc: "teapot" }, { emoji: "🍵", desc: "teacup tea" }, { emoji: "🍶", desc: "sake" },
        { emoji: "🍾", desc: "bottle popping cork champagne" }, { emoji: "🍷", desc: "wine glass" }, { emoji: "🍸", desc: "cocktail glass martini" }, { emoji: "🍹", desc: "tropical drink" }, { emoji: "🍺", desc: "beer mug" }, { emoji: "🍻", desc: "clinking beer mugs cheers" }, { emoji: "🥂", desc: "clinking glasses toast" }, { emoji: "🥃", desc: "tumbler glass whiskey" }, { emoji: "🥤", desc: "cup straw soda" }, { emoji: "🧋", desc: "bubble tea boba" }, { emoji: "🧃", desc: "beverage box juice" }, { emoji: "🧉", desc: "mate" }, { emoji: "🧊", desc: "ice cube" }, { emoji: "🥢", desc: "chopsticks" }, { emoji: "🍽️", desc: "fork knife plate" }, { emoji: "🍴", desc: "fork knife" }, { emoji: "🥄", desc: "spoon" }, { emoji: "🔪", desc: "kitchen knife" }, { emoji: "🏺", desc: "amphora vase" }
      ],
    },
    {
      name: "Travel & Places",
      emojis: [
        { emoji: "🚗", desc: "car automobile" }, { emoji: "🚕", desc: "taxi cab" }, { emoji: "🚙", desc: "sport utility vehicle suv" }, { emoji: "🚌", desc: "bus" }, { emoji: "🚎", desc: "trolleybus" }, { emoji: "🏎️", desc: "racing car" }, { emoji: "🚓", desc: "police car" }, { emoji: "🚑", desc: "ambulance" }, { emoji: "🚒", desc: "fire engine truck" }, { emoji: "🚐", desc: "minibus van" }, { emoji: "🛻", desc: "pickup truck" }, { emoji: "🚚", desc: "delivery truck" }, { emoji: "🚛", desc: "articulated lorry truck" }, { emoji: "🚜", desc: "tractor farm" }, { emoji: "🦯", desc: "white cane" }, { emoji: "🦽", desc: "manual wheelchair" }, { emoji: "🦼", desc: "motorized wheelchair" }, { emoji: "🛴", desc: "kick scooter" }, { emoji: "🚲", desc: "bicycle bike" }, { emoji: "🛵", desc: "motor scooter" }, { emoji: "🏍️", desc: "motorcycle" }, { emoji: "🛺", desc: "auto rickshaw tuk tuk" },
        { emoji: "🚨", desc: "police car light siren" }, { emoji: "🚔", desc: "oncoming police car" }, { emoji: "🚍", desc: "oncoming bus" }, { emoji: "🚘", desc: "oncoming automobile" }, { emoji: "🚖", desc: "oncoming taxi" }, { emoji: "🚡", desc: "aerial tramway" }, { emoji: "🚠", desc: "mountain cableway" }, { emoji: "🚟", desc: "suspension railway" }, { emoji: "🚃", desc: "railway car" }, { emoji: "🚋", desc: "tram car" }, { emoji: "🚞", desc: "mountain railway" }, { emoji: "🚝", desc: "monorail" }, { emoji: "🚄", desc: "high speed train" }, { emoji: "🚅", desc: "bullet train" }, { emoji: "🚈", desc: "light rail" }, { emoji: "🚂", desc: "locomotive train" }, { emoji: "🚆", desc: "train" }, { emoji: "🚇", desc: "metro subway" }, { emoji: "🚊", desc: "tram" }, { emoji: "🚉", desc: "station" }, { emoji: "✈️", desc: "airplane plane" }, { emoji: "🛫", desc: "airplane departure takeoff" },
        { emoji: "🛬", desc: "airplane arrival landing" }, { emoji: "🛩️", desc: "small airplane" }, { emoji: "💺", desc: "seat" }, { emoji: "🛰️", desc: "satellite" }, { emoji: "🚀", desc: "rocket spaceship" }, { emoji: "🛸", desc: "flying saucer ufo" }, { emoji: "🚁", desc: "helicopter" }, { emoji: "🛶", desc: "canoe kayak" }, { emoji: "⛵", desc: "sailboat" }, { emoji: "🚤", desc: "speedboat" }, { emoji: "🛥️", desc: "motor boat" }, { emoji: "🛳️", desc: "passenger ship cruise" }, { emoji: "⛴️", desc: "ferry" }, { emoji: "🚢", desc: "ship" }, { emoji: "⚓", desc: "anchor" }, { emoji: "🪝", desc: "hook" }, { emoji: "⛽", desc: "fuel pump gas station" }, { emoji: "🚧", desc: "construction barrier" }, { emoji: "🚦", desc: "vertical traffic light" }, { emoji: "🚥", desc: "horizontal traffic light" }, { emoji: "🚏", desc: "bus stop" }, { emoji: "🗺️", desc: "world map" },
        { emoji: "🗿", desc: "moai statue" }, { emoji: "🗽", desc: "statue liberty" }, { emoji: "🗼", desc: "tokyo tower" }, { emoji: "🏰", desc: "castle" }, { emoji: "🏯", desc: "japanese castle" }, { emoji: "🏟️", desc: "stadium" }, { emoji: "🎡", desc: "ferris wheel" }, { emoji: "🎢", desc: "roller coaster" }, { emoji: "🎠", desc: "carousel horse" }, { emoji: "⛲", desc: "fountain" }, { emoji: "⛱️", desc: "umbrella ground beach" }, { emoji: "🏖️", desc: "beach umbrella" }, { emoji: "🏝️", desc: "desert island" }, { emoji: "🏜️", desc: "desert" }, { emoji: "🌋", desc: "volcano" }, { emoji: "⛰️", desc: "mountain" }, { emoji: "🏔️", desc: "snow capped mountain" }, { emoji: "🗻", desc: "mount fuji" }, { emoji: "🏕️", desc: "camping tent" }, { emoji: "⛺", desc: "tent" }, { emoji: "🛖", desc: "hut" }, { emoji: "🏠", desc: "house" },
        { emoji: "🏡", desc: "house garden" }, { emoji: "🏘️", desc: "houses" }, { emoji: "🏚️", desc: "derelict house" }, { emoji: "🏗️", desc: "building construction" }, { emoji: "🏭", desc: "factory" }, { emoji: "🏢", desc: "office building" }, { emoji: "🏬", desc: "department store" }, { emoji: "🏣", desc: "japanese post office" }, { emoji: "🏤", desc: "post office" }, { emoji: "🏥", desc: "hospital" }, { emoji: "🏦", desc: "bank" }, { emoji: "🏨", desc: "hotel" }, { emoji: "🏪", desc: "convenience store" }, { emoji: "🏫", desc: "school" }, { emoji: "🏩", desc: "love hotel" }, { emoji: "💒", desc: "wedding chapel" }, { emoji: "🏛️", desc: "classical building" }, { emoji: "⛪", desc: "church" }, { emoji: "🕌", desc: "mosque" }, { emoji: "🕍", desc: "synagogue" }, { emoji: "🛕", desc: "hindu temple" }, { emoji: "🕋", desc: "kaaba mecca" },
        { emoji: "⛩️", desc: "shinto shrine torii" }, { emoji: "🛤️", desc: "railway track" }, { emoji: "🛣️", desc: "motorway highway" }, { emoji: "🗾", desc: "map japan" }, { emoji: "🎑", desc: "moon viewing ceremony" }, { emoji: "🏞️", desc: "national park" }, { emoji: "🌅", desc: "sunrise" }, { emoji: "🌄", desc: "sunrise mountains" }, { emoji: "🌠", desc: "shooting star" }, { emoji: "🎇", desc: "sparkler firework" }, { emoji: "🎆", desc: "fireworks" }, { emoji: "🌇", desc: "sunset" }, { emoji: "🌆", desc: "cityscape dusk" }, { emoji: "🏙️", desc: "cityscape" }, { emoji: "🌃", desc: "night stars" }, { emoji: "🌌", desc: "milky way galaxy" }, { emoji: "🌉", desc: "bridge night" }, { emoji: "🌁", desc: "foggy" }
      ],
    },
    {
      name: "Activities",
      emojis: [
        { emoji: "⚽", desc: "soccer ball football" }, { emoji: "🏀", desc: "basketball" }, { emoji: "🏈", desc: "american football" }, { emoji: "⚾", desc: "baseball" }, { emoji: "🥎", desc: "softball" }, { emoji: "🎾", desc: "tennis" }, { emoji: "🏐", desc: "volleyball" }, { emoji: "🏉", desc: "rugby football" }, { emoji: "🥏", desc: "flying disc frisbee" }, { emoji: "🎱", desc: "pool 8 ball billiard" }, { emoji: "🪀", desc: "yo-yo" }, { emoji: "🏓", desc: "ping pong table tennis" }, { emoji: "🏸", desc: "badminton" }, { emoji: "🏒", desc: "ice hockey" }, { emoji: "🏑", desc: "field hockey" }, { emoji: "🥍", desc: "lacrosse" }, { emoji: "🏏", desc: "cricket game" }, { emoji: "🪃", desc: "boomerang" }, { emoji: "🥅", desc: "goal net" }, { emoji: "⛳", desc: "flag hole golf" }, { emoji: "🪁", desc: "kite" }, { emoji: "🏹", desc: "bow arrow archery" },
        { emoji: "🎣", desc: "fishing pole" }, { emoji: "🤿", desc: "diving mask snorkel" }, { emoji: "🥊", desc: "boxing glove" }, { emoji: "🥋", desc: "martial arts uniform" }, { emoji: "🎽", desc: "running shirt" }, { emoji: "🛹", desc: "skateboard" }, { emoji: "🛼", desc: "roller skate" }, { emoji: "🛷", desc: "sled" }, { emoji: "⛸️", desc: "ice skate" }, { emoji: "🥌", desc: "curling stone" }, { emoji: "🎿", desc: "skis" }, { emoji: "⛷️", desc: "skier" }, { emoji: "🏂", desc: "snowboarder" }, { emoji: "🪂", desc: "parachute" }, { emoji: "🏋️", desc: "person lifting weights" }, { emoji: "🤼", desc: "people wrestling" }, { emoji: "🤸", desc: "person cartwheeling" }, { emoji: "🤺", desc: "person fencing" }, { emoji: "⛹️", desc: "person bouncing ball" }, { emoji: "🤾", desc: "person handball" }, { emoji: "🏌️", desc: "person golfing" }, { emoji: "🏇", desc: "horse racing" },
        { emoji: "🧘", desc: "person lotus yoga meditation" }, { emoji: "🏄", desc: "person surfing" }, { emoji: "🏊", desc: "person swimming" }, { emoji: "🤽", desc: "person water polo" }, { emoji: "🚣", desc: "person rowing boat" }, { emoji: "🧗", desc: "person climbing" }, { emoji: "🚵", desc: "person mountain biking" }, { emoji: "🚴", desc: "person biking" }, { emoji: "🏆", desc: "trophy winner" }, { emoji: "🥇", desc: "1st place medal gold" }, { emoji: "🥈", desc: "2nd place medal silver" }, { emoji: "🥉", desc: "3rd place medal bronze" }, { emoji: "🏅", desc: "sports medal" }, { emoji: "🎖️", desc: "military medal" }, { emoji: "🏵️", desc: "rosette" }, { emoji: "🎗️", desc: "reminder ribbon" }, { emoji: "🎫", desc: "ticket" }, { emoji: "🎟️", desc: "admission tickets" }, { emoji: "🎪", desc: "circus tent" }, { emoji: "🤹", desc: "person juggling" }, { emoji: "🎭", desc: "performing arts theater" }, { emoji: "🩰", desc: "ballet shoes" },
        { emoji: "🎨", desc: "artist palette paint" }, { emoji: "🎬", desc: "clapper board movie" }, { emoji: "🎤", desc: "microphone karaoke" }, { emoji: "🎧", desc: "headphone music" }, { emoji: "🎼", desc: "musical score" }, { emoji: "🎹", desc: "musical keyboard piano" }, { emoji: "🥁", desc: "drum" }, { emoji: "🪘", desc: "long drum" }, { emoji: "🎷", desc: "saxophone" }, { emoji: "🎺", desc: "trumpet" }, { emoji: "🪗", desc: "accordion" }, { emoji: "🎸", desc: "guitar" }, { emoji: "🪕", desc: "banjo" }, { emoji: "🎻", desc: "violin" }, { emoji: "🎲", desc: "game die dice" }, { emoji: "♟️", desc: "chess pawn" }, { emoji: "🎯", desc: "bullseye target dart" }, { emoji: "🎳", desc: "bowling" }, { emoji: "🎮", desc: "video game controller" }, { emoji: "🎰", desc: "slot machine casino" }, { emoji: "🧩", desc: "puzzle piece" }
      ],
    },
    {
      name: "Objects",
      emojis: [
        { emoji: "⌚", desc: "watch time" }, { emoji: "📱", desc: "mobile phone smartphone" }, { emoji: "📲", desc: "mobile phone arrow" }, { emoji: "💻", desc: "laptop computer" }, { emoji: "⌨️", desc: "keyboard" }, { emoji: "🖥️", desc: "desktop computer monitor" }, { emoji: "🖨️", desc: "printer" }, { emoji: "🖱️", desc: "computer mouse" }, { emoji: "🖲️", desc: "trackball" }, { emoji: "🕹️", desc: "joystick" }, { emoji: "🗜️", desc: "clamp compression" }, { emoji: "💽", desc: "computer disk minidisc" }, { emoji: "💾", desc: "floppy disk save" }, { emoji: "💿", desc: "optical disk cd" }, { emoji: "📀", desc: "dvd" }, { emoji: "📼", desc: "videocassette vhs" }, { emoji: "📷", desc: "camera" }, { emoji: "📸", desc: "camera flash" }, { emoji: "📹", desc: "video camera" }, { emoji: "🎥", desc: "movie camera" }, { emoji: "📽️", desc: "film projector" }, { emoji: "🎞️", desc: "film frames" },
        { emoji: "📞", desc: "telephone receiver" }, { emoji: "☎️", desc: "telephone" }, { emoji: "📟", desc: "pager" }, { emoji: "📠", desc: "fax machine" }, { emoji: "📺", desc: "television tv" }, { emoji: "📻", desc: "radio" }, { emoji: "🎙️", desc: "studio microphone" }, { emoji: "🎚️", desc: "level slider" }, { emoji: "🎛️", desc: "control knobs" }, { emoji: "🧭", desc: "compass" }, { emoji: "⏱️", desc: "stopwatch" }, { emoji: "⏲️", desc: "timer clock" }, { emoji: "⏰", desc: "alarm clock" }, { emoji: "🕰️", desc: "mantelpiece clock" }, { emoji: "⌛", desc: "hourglass done" }, { emoji: "⏳", desc: "hourglass not done" }, { emoji: "📡", desc: "satellite antenna" }, { emoji: "🔋", desc: "battery" }, { emoji: "🔌", desc: "electric plug" }, { emoji: "💡", desc: "light bulb idea" }, { emoji: "🔦", desc: "flashlight" }, { emoji: "🕯️", desc: "candle" },
        { emoji: "🪔", desc: "diya lamp" }, { emoji: "🧯", desc: "fire extinguisher" }, { emoji: "🛢️", desc: "oil drum barrel" }, { emoji: "💸", desc: "money wings flying" }, { emoji: "💵", desc: "dollar banknote" }, { emoji: "💴", desc: "yen banknote" }, { emoji: "💶", desc: "euro banknote" }, { emoji: "💷", desc: "pound banknote" }, { emoji: "🪙", desc: "coin" }, { emoji: "💰", desc: "money bag" }, { emoji: "💳", desc: "credit card" }, { emoji: "💎", desc: "gem stone diamond" }, { emoji: "⚖️", desc: "balance scale justice" }, { emoji: "🪜", desc: "ladder" }, { emoji: "🧰", desc: "toolbox" }, { emoji: "🪛", desc: "screwdriver" }, { emoji: "🔧", desc: "wrench spanner" }, { emoji: "🔨", desc: "hammer" }, { emoji: "⚒️", desc: "hammer pick" }, { emoji: "🛠️", desc: "hammer wrench tools" }, { emoji: "⛏️", desc: "pick" }, { emoji: "🪚", desc: "carpentry saw" },
        { emoji: "🔩", desc: "nut bolt" }, { emoji: "⚙️", desc: "gear cog settings" }, { emoji: "🪤", desc: "mouse trap" }, { emoji: "🧱", desc: "brick" }, { emoji: "⛓️", desc: "chains" }, { emoji: "🧲", desc: "magnet" }, { emoji: "🔫", desc: "water pistol gun" }, { emoji: "💣", desc: "bomb" }, { emoji: "🧨", desc: "firecracker dynamite" }, { emoji: "🪓", desc: "axe" }, { emoji: "🔪", desc: "kitchen knife" }, { emoji: "🗡️", desc: "dagger sword" }, { emoji: "⚔️", desc: "crossed swords" }, { emoji: "🛡️", desc: "shield" }, { emoji: "🚬", desc: "cigarette smoking" }, { emoji: "⚰️", desc: "coffin" }, { emoji: "🪦", desc: "headstone grave" }, { emoji: "⚱️", desc: "funeral urn" }, { emoji: "🏺", desc: "amphora vase" }, { emoji: "🔮", desc: "crystal ball fortune" }, { emoji: "📿", desc: "prayer beads" }, { emoji: "🧿", desc: "nazar amulet evil eye" },
        { emoji: "💈", desc: "barber pole" }, { emoji: "⚗️", desc: "alembic chemistry" }, { emoji: "🔭", desc: "telescope" }, { emoji: "🔬", desc: "microscope" }, { emoji: "🕳️", desc: "hole" }, { emoji: "🩹", desc: "adhesive bandage" }, { emoji: "🩺", desc: "stethoscope" }, { emoji: "💊", desc: "pill medicine" }, { emoji: "💉", desc: "syringe injection" }, { emoji: "🩸", desc: "drop blood" }, { emoji: "🧬", desc: "dna" }, { emoji: "🦠", desc: "microbe bacteria virus" }, { emoji: "🧫", desc: "petri dish" }, { emoji: "🧪", desc: "test tube" }, { emoji: "🌡️", desc: "thermometer temperature" }, { emoji: "🧹", desc: "broom" }, { emoji: "🪠", desc: "plunger" }, { emoji: "🧺", desc: "basket laundry" }, { emoji: "🧻", desc: "roll paper toilet" }, { emoji: "🚽", desc: "toilet" }, { emoji: "🚰", desc: "potable water tap" }, { emoji: "🚿", desc: "shower" },
        { emoji: "🛁", desc: "bathtub" }, { emoji: "🛀", desc: "person bath" }, { emoji: "🧼", desc: "soap" }, { emoji: "🪥", desc: "toothbrush" }, { emoji: "🪒", desc: "razor" }, { emoji: "🧽", desc: "sponge" }, { emoji: "🪣", desc: "bucket" }, { emoji: "🧴", desc: "lotion bottle" }, { emoji: "🛎️", desc: "bellhop bell" }, { emoji: "🔑", desc: "key" }, { emoji: "🗝️", desc: "old key" }, { emoji: "🚪", desc: "door" }, { emoji: "🪑", desc: "chair seat" }, { emoji: "🛋️", desc: "couch sofa" }, { emoji: "🛏️", desc: "bed" }, { emoji: "🛌", desc: "person bed sleeping" }, { emoji: "🧸", desc: "teddy bear" }, { emoji: "🪆", desc: "nesting dolls matryoshka" }, { emoji: "🖼️", desc: "framed picture" }, { emoji: "🪞", desc: "mirror" }, { emoji: "🪟", desc: "window" }, { emoji: "🛍️", desc: "shopping bags" },
        { emoji: "🛒", desc: "shopping cart" }, { emoji: "🎁", desc: "wrapped gift present" }, { emoji: "🎈", desc: "balloon" }, { emoji: "🎏", desc: "carp streamer" }, { emoji: "🎀", desc: "ribbon" }, { emoji: "🪄", desc: "magic wand" }, { emoji: "🪅", desc: "pinata" }, { emoji: "🎊", desc: "confetti ball" }, { emoji: "🎉", desc: "party popper celebration" }, { emoji: "🎎", desc: "japanese dolls" }, { emoji: "🏮", desc: "red paper lantern" }, { emoji: "🎐", desc: "wind chime" }, { emoji: "🧧", desc: "red envelope" }, { emoji: "✉️", desc: "envelope mail" }, { emoji: "📩", desc: "envelope arrow incoming" }, { emoji: "📨", desc: "incoming envelope" }, { emoji: "📧", desc: "e-mail email" }, { emoji: "💌", desc: "love letter" }, { emoji: "📥", desc: "inbox tray" }, { emoji: "📤", desc: "outbox tray" }, { emoji: "📦", desc: "package box" }, { emoji: "🏷️", desc: "label tag" },
        { emoji: "🪧", desc: "placard sign" }, { emoji: "📪", desc: "closed mailbox flag down" }, { emoji: "📫", desc: "closed mailbox flag up" }, { emoji: "📬", desc: "open mailbox flag up" }, { emoji: "📭", desc: "open mailbox flag down" }, { emoji: "📮", desc: "postbox" }, { emoji: "📯", desc: "postal horn" }, { emoji: "📜", desc: "scroll" }, { emoji: "📃", desc: "page curl" }, { emoji: "📄", desc: "page facing up document" }, { emoji: "📑", desc: "bookmark tabs" }, { emoji: "🧾", desc: "receipt" }, { emoji: "📊", desc: "bar chart graph" }, { emoji: "📈", desc: "chart increasing" }, { emoji: "📉", desc: "chart decreasing" }, { emoji: "🗒️", desc: "spiral notepad" }, { emoji: "🗓️", desc: "spiral calendar" }, { emoji: "📆", desc: "tear off calendar" }, { emoji: "📅", desc: "calendar" }, { emoji: "🗑️", desc: "wastebasket trash" }, { emoji: "📇", desc: "card index" }, { emoji: "🗃️", desc: "card file box" },
        { emoji: "🗳️", desc: "ballot box" }, { emoji: "🗄️", desc: "file cabinet" }, { emoji: "📋", desc: "clipboard" }, { emoji: "📁", desc: "file folder" }, { emoji: "📂", desc: "open file folder" }, { emoji: "🗂️", desc: "card index dividers" }, { emoji: "🗞️", desc: "rolled up newspaper" }, { emoji: "📰", desc: "newspaper" }, { emoji: "📓", desc: "notebook" }, { emoji: "📔", desc: "notebook decorative cover" }, { emoji: "📒", desc: "ledger" }, { emoji: "📕", desc: "closed book" }, { emoji: "📗", desc: "green book" }, { emoji: "📘", desc: "blue book" }, { emoji: "📙", desc: "orange book" }, { emoji: "📚", desc: "books" }, { emoji: "📖", desc: "open book" }, { emoji: "🔖", desc: "bookmark" }, { emoji: "🧷", desc: "safety pin" }, { emoji: "🔗", desc: "link chain" }, { emoji: "📎", desc: "paperclip" }, { emoji: "🖇️", desc: "linked paperclips" },
        { emoji: "📐", desc: "triangular ruler" }, { emoji: "📏", desc: "straight ruler" }, { emoji: "🧮", desc: "abacus" }, { emoji: "📌", desc: "pushpin" }, { emoji: "📍", desc: "round pushpin location" }, { emoji: "✂️", desc: "scissors" }, { emoji: "🖊️", desc: "pen" }, { emoji: "🖋️", desc: "fountain pen" }, { emoji: "✒️", desc: "black nib" }, { emoji: "🖌️", desc: "paintbrush" }, { emoji: "🖍️", desc: "crayon" }, { emoji: "📝", desc: "memo note" }, { emoji: "✏️", desc: "pencil" }, { emoji: "🔍", desc: "magnifying glass left search" }, { emoji: "🔎", desc: "magnifying glass right" }, { emoji: "🔏", desc: "locked pen" }, { emoji: "🔐", desc: "locked key" }, { emoji: "🔒", desc: "locked padlock" }, { emoji: "🔓", desc: "unlocked padlock" }
      ],
    },
    {
      name: "Symbols",
      emojis: [
        { emoji: "❤️", desc: "red heart love" }, { emoji: "🧡", desc: "orange heart" }, { emoji: "💛", desc: "yellow heart" }, { emoji: "💚", desc: "green heart" }, { emoji: "💙", desc: "blue heart" }, { emoji: "💜", desc: "purple heart" }, { emoji: "🖤", desc: "black heart" }, { emoji: "🤍", desc: "white heart" }, { emoji: "🤎", desc: "brown heart" }, { emoji: "💔", desc: "broken heart" }, { emoji: "❣️", desc: "heart exclamation" }, { emoji: "💕", desc: "two hearts" }, { emoji: "💞", desc: "revolving hearts" }, { emoji: "💓", desc: "beating heart" }, { emoji: "💗", desc: "growing heart" }, { emoji: "💖", desc: "sparkling heart" }, { emoji: "💘", desc: "heart arrow cupid" }, { emoji: "💝", desc: "heart ribbon" }, { emoji: "💟", desc: "heart decoration" }, { emoji: "☮️", desc: "peace symbol" }, { emoji: "✝️", desc: "latin cross christian" }, { emoji: "☪️", desc: "star crescent islam" },
        { emoji: "🕉️", desc: "om hindu" }, { emoji: "☸️", desc: "wheel dharma buddhism" }, { emoji: "✡️", desc: "star david jewish" }, { emoji: "🔯", desc: "dotted six pointed star" }, { emoji: "🕎", desc: "menorah" }, { emoji: "☯️", desc: "yin yang" }, { emoji: "☦️", desc: "orthodox cross" }, { emoji: "🛐", desc: "place worship" }, { emoji: "⛎", desc: "ophiuchus zodiac" }, { emoji: "♈", desc: "aries zodiac" }, { emoji: "♉", desc: "taurus zodiac" }, { emoji: "♊", desc: "gemini zodiac" }, { emoji: "♋", desc: "cancer zodiac" }, { emoji: "♌", desc: "leo zodiac" }, { emoji: "♍", desc: "virgo zodiac" }, { emoji: "♎", desc: "libra zodiac" }, { emoji: "♏", desc: "scorpio zodiac" }, { emoji: "♐", desc: "sagittarius zodiac" }, { emoji: "♑", desc: "capricorn zodiac" }, { emoji: "♒", desc: "aquarius zodiac" }, { emoji: "♓", desc: "pisces zodiac" }, { emoji: "🆔", desc: "id button" }, { emoji: "⚛️", desc: "atom symbol" },
        { emoji: "🉑", desc: "japanese acceptable" }, { emoji: "☢️", desc: "radioactive" }, { emoji: "☣️", desc: "biohazard" }, { emoji: "📴", desc: "mobile phone off" }, { emoji: "📳", desc: "vibration mode" }, { emoji: "🈶", desc: "japanese not free charge" }, { emoji: "🈚", desc: "japanese free charge" }, { emoji: "🈸", desc: "japanese application" }, { emoji: "🈺", desc: "japanese open business" }, { emoji: "🈷️", desc: "japanese monthly amount" }, { emoji: "✴️", desc: "eight pointed star" }, { emoji: "🆚", desc: "vs versus button" }, { emoji: "💮", desc: "white flower" }, { emoji: "🉐", desc: "japanese bargain" }, { emoji: "㊙️", desc: "japanese secret" }, { emoji: "㊗️", desc: "japanese congratulations" }, { emoji: "🈴", desc: "japanese passing grade" }, { emoji: "🈵", desc: "japanese no vacancy" }, { emoji: "🈹", desc: "japanese discount" }, { emoji: "🈲", desc: "japanese prohibited" }, { emoji: "🅰️", desc: "a button blood type" }, { emoji: "🅱️", desc: "b button blood type" },
        { emoji: "🆎", desc: "ab button blood type" }, { emoji: "🆑", desc: "cl button" }, { emoji: "🅾️", desc: "o button blood type" }, { emoji: "🆘", desc: "sos button help" }, { emoji: "❌", desc: "cross mark wrong" }, { emoji: "⭕", desc: "hollow red circle" }, { emoji: "🛑", desc: "stop sign" }, { emoji: "⛔", desc: "no entry prohibited" }, { emoji: "📛", desc: "name badge" }, { emoji: "🚫", desc: "prohibited forbidden" }, { emoji: "💯", desc: "hundred points perfect" }, { emoji: "💢", desc: "anger symbol" }, { emoji: "♨️", desc: "hot springs" }, { emoji: "🚷", desc: "no pedestrians" }, { emoji: "🚯", desc: "no littering" }, { emoji: "🚳", desc: "no bicycles" }, { emoji: "🚱", desc: "non potable water" }, { emoji: "🔞", desc: "no one under eighteen" }, { emoji: "📵", desc: "no mobile phones" }, { emoji: "🚭", desc: "no smoking" }, { emoji: "❗", desc: "exclamation mark" }, { emoji: "❕", desc: "white exclamation mark" },
        { emoji: "❓", desc: "question mark" }, { emoji: "❔", desc: "white question mark" }, { emoji: "‼️", desc: "double exclamation mark" }, { emoji: "⁉️", desc: "exclamation question mark" }, { emoji: "🔅", desc: "dim button brightness" }, { emoji: "🔆", desc: "bright button brightness" }, { emoji: "〽️", desc: "part alternation mark" }, { emoji: "⚠️", desc: "warning" }, { emoji: "🚸", desc: "children crossing" }, { emoji: "🔱", desc: "trident emblem" }, { emoji: "⚜️", desc: "fleur de lis" }, { emoji: "🔰", desc: "japanese symbol beginner" }, { emoji: "♻️", desc: "recycling symbol" }, { emoji: "✅", desc: "check mark button correct" }, { emoji: "🈯", desc: "japanese reserved" }, { emoji: "💹", desc: "chart increasing yen" }, { emoji: "❇️", desc: "sparkle" }, { emoji: "✳️", desc: "eight spoked asterisk" }, { emoji: "❎", desc: "cross mark button" }, { emoji: "🌐", desc: "globe meridians world" }, { emoji: "💠", desc: "diamond dot" }, { emoji: "Ⓜ️", desc: "circled m metro" },
        { emoji: "🌀", desc: "cyclone hurricane" }, { emoji: "💤", desc: "zzz sleep" }, { emoji: "🏧", desc: "atm sign" }, { emoji: "🚾", desc: "water closet wc toilet" }, { emoji: "♿", desc: "wheelchair symbol accessible" }, { emoji: "🅿️", desc: "p button parking" }, { emoji: "🛗", desc: "elevator" }, { emoji: "🈳", desc: "japanese vacancy" }, { emoji: "🈂️", desc: "japanese service charge" }, { emoji: "🛂", desc: "passport control" }, { emoji: "🛃", desc: "customs" }, { emoji: "🛄", desc: "baggage claim" }, { emoji: "🛅", desc: "left luggage" }, { emoji: "🚹", desc: "mens room male" }, { emoji: "🚺", desc: "womens room female" }, { emoji: "🚼", desc: "baby symbol" }, { emoji: "⚧️", desc: "transgender symbol" }, { emoji: "🚻", desc: "restroom" }, { emoji: "🚮", desc: "litter bin sign" }, { emoji: "🎦", desc: "cinema" }, { emoji: "📶", desc: "antenna bars signal" }, { emoji: "🈁", desc: "japanese here" },
        { emoji: "🔣", desc: "input symbols" }, { emoji: "ℹ️", desc: "information" }, { emoji: "🔤", desc: "input latin letters abc" }, { emoji: "🔡", desc: "input latin lowercase" }, { emoji: "🔠", desc: "input latin uppercase" }, { emoji: "🆖", desc: "ng button" }, { emoji: "🆗", desc: "ok button" }, { emoji: "🆙", desc: "up button" }, { emoji: "🆒", desc: "cool button" }, { emoji: "🆕", desc: "new button" }, { emoji: "🆓", desc: "free button" }, { emoji: "0️⃣", desc: "keycap zero" }, { emoji: "1️⃣", desc: "keycap one" }, { emoji: "2️⃣", desc: "keycap two" }, { emoji: "3️⃣", desc: "keycap three" }, { emoji: "4️⃣", desc: "keycap four" }, { emoji: "5️⃣", desc: "keycap five" }, { emoji: "6️⃣", desc: "keycap six" }, { emoji: "7️⃣", desc: "keycap seven" }, { emoji: "8️⃣", desc: "keycap eight" }, { emoji: "9️⃣", desc: "keycap nine" }, { emoji: "🔟", desc: "keycap ten" },
        { emoji: "🔢", desc: "input numbers" }, { emoji: "#️⃣", desc: "keycap hash" }, { emoji: "*️⃣", desc: "keycap asterisk" }, { emoji: "⏏️", desc: "eject button" }, { emoji: "▶️", desc: "play button" }, { emoji: "⏸️", desc: "pause button" }, { emoji: "⏯️", desc: "play pause button" }, { emoji: "⏹️", desc: "stop button" }, { emoji: "⏺️", desc: "record button" }, { emoji: "⏭️", desc: "next track button" }, { emoji: "⏮️", desc: "last track button" }, { emoji: "⏩", desc: "fast forward button" }, { emoji: "⏪", desc: "fast reverse button" }, { emoji: "⏫", desc: "fast up button" }, { emoji: "⏬", desc: "fast down button" }, { emoji: "◀️", desc: "reverse button" }, { emoji: "🔼", desc: "upwards button" }, { emoji: "🔽", desc: "downwards button" }, { emoji: "➡️", desc: "right arrow" }, { emoji: "⬅️", desc: "left arrow" }, { emoji: "⬆️", desc: "up arrow" }, { emoji: "⬇️", desc: "down arrow" },
        { emoji: "↗️", desc: "up right arrow" }, { emoji: "↘️", desc: "down right arrow" }, { emoji: "↙️", desc: "down left arrow" }, { emoji: "↖️", desc: "up left arrow" }, { emoji: "↕️", desc: "up down arrow" }, { emoji: "↔️", desc: "left right arrow" }, { emoji: "↪️", desc: "right arrow curving left" }, { emoji: "↩️", desc: "left arrow curving right" }, { emoji: "⤴️", desc: "right arrow curving up" }, { emoji: "⤵️", desc: "right arrow curving down" }, { emoji: "🔀", desc: "shuffle tracks button" }, { emoji: "🔁", desc: "repeat button" }, { emoji: "🔂", desc: "repeat single button" }, { emoji: "🔄", desc: "counterclockwise arrows refresh" }, { emoji: "🔃", desc: "clockwise arrows" }, { emoji: "🎵", desc: "musical note" }, { emoji: "🎶", desc: "musical notes" }, { emoji: "➕", desc: "plus" }, { emoji: "➖", desc: "minus" }, { emoji: "➗", desc: "divide" }, { emoji: "✖️", desc: "multiply" }, { emoji: "♾️", desc: "infinity" },
        { emoji: "💲", desc: "heavy dollar sign" }, { emoji: "💱", desc: "currency exchange" }, { emoji: "™️", desc: "trade mark" }, { emoji: "©️", desc: "copyright" }, { emoji: "®️", desc: "registered" }, { emoji: "〰️", desc: "wavy dash" }, { emoji: "➰", desc: "curly loop" }, { emoji: "➿", desc: "double curly loop" }, { emoji: "🔚", desc: "end arrow" }, { emoji: "🔙", desc: "back arrow" }, { emoji: "🔛", desc: "on arrow" }, { emoji: "🔝", desc: "top arrow" }, { emoji: "🔜", desc: "soon arrow" }, { emoji: "✔️", desc: "check mark correct" }, { emoji: "☑️", desc: "check box mark" }, { emoji: "🔘", desc: "radio button" }, { emoji: "🔴", desc: "red circle" }, { emoji: "🟠", desc: "orange circle" }, { emoji: "🟡", desc: "yellow circle" }, { emoji: "🟢", desc: "green circle" }, { emoji: "🔵", desc: "blue circle" }, { emoji: "🟣", desc: "purple circle" },
        { emoji: "⚫", desc: "black circle" }, { emoji: "⚪", desc: "white circle" }, { emoji: "🟤", desc: "brown circle" }, { emoji: "🔺", desc: "red triangle up" }, { emoji: "🔻", desc: "red triangle down" }, { emoji: "🔸", desc: "small orange diamond" }, { emoji: "🔹", desc: "small blue diamond" }, { emoji: "🔶", desc: "large orange diamond" }, { emoji: "🔷", desc: "large blue diamond" }, { emoji: "🔳", desc: "white square button" }, { emoji: "🔲", desc: "black square button" }, { emoji: "▪️", desc: "black small square" }, { emoji: "▫️", desc: "white small square" }, { emoji: "◾", desc: "black medium small square" }, { emoji: "◽", desc: "white medium small square" }, { emoji: "◼️", desc: "black medium square" }, { emoji: "◻️", desc: "white medium square" }, { emoji: "🟥", desc: "red square" }, { emoji: "🟧", desc: "orange square" }, { emoji: "🟨", desc: "yellow square" }, { emoji: "🟩", desc: "green square" }, { emoji: "🟦", desc: "blue square" },
        { emoji: "🟪", desc: "purple square" }, { emoji: "⬛", desc: "black large square" }, { emoji: "⬜", desc: "white large square" }, { emoji: "🟫", desc: "brown square" }, { emoji: "🔈", desc: "speaker low volume" }, { emoji: "🔇", desc: "muted speaker" }, { emoji: "🔉", desc: "speaker medium volume" }, { emoji: "🔊", desc: "speaker high volume loud" }, { emoji: "🔔", desc: "bell notification" }, { emoji: "🔕", desc: "bell slash muted" }, { emoji: "📣", desc: "megaphone" }, { emoji: "📢", desc: "loudspeaker" }, { emoji: "👁️‍🗨️", desc: "eye speech bubble" }, { emoji: "💬", desc: "speech balloon comment" }, { emoji: "💭", desc: "thought balloon thinking" }, { emoji: "🗯️", desc: "right anger bubble" }, { emoji: "♠️", desc: "spade suit cards" }, { emoji: "♣️", desc: "club suit cards" }, { emoji: "♥️", desc: "heart suit cards" }, { emoji: "♦️", desc: "diamond suit cards" }, { emoji: "🃏", desc: "joker card" }, { emoji: "🎴", desc: "flower playing cards" }, { emoji: "🀄", desc: "mahjong red dragon" }
      ],
    },
    {
      name: "Flags",
      emojis: [
        { emoji: "🏳️", desc: "white flag" }, { emoji: "🏴", desc: "black flag" }, { emoji: "🏴‍☠️", desc: "pirate flag" }, { emoji: "🏁", desc: "chequered flag racing" }, { emoji: "🚩", desc: "triangular flag" }, { emoji: "🎌", desc: "crossed flags japan" }, { emoji: "🏳️‍🌈", desc: "rainbow flag pride lgbt" }, { emoji: "🏳️‍⚧️", desc: "transgender flag" }, { emoji: "🇺🇳", desc: "united nations flag" }, { emoji: "🇦🇫", desc: "afghanistan flag" }, { emoji: "🇦🇱", desc: "albania flag" }, { emoji: "🇩🇿", desc: "algeria flag" }, { emoji: "🇦🇸", desc: "american samoa flag" }, { emoji: "🇦🇩", desc: "andorra flag" }, { emoji: "🇦🇴", desc: "angola flag" }, { emoji: "🇦🇮", desc: "anguilla flag" }, { emoji: "🇦🇶", desc: "antarctica flag" }, { emoji: "🇦🇬", desc: "antigua barbuda flag" }, { emoji: "🇦🇷", desc: "argentina flag" }, { emoji: "🇦🇲", desc: "armenia flag" }, { emoji: "🇦🇼", desc: "aruba flag" }, { emoji: "🇦🇺", desc: "australia flag" },
        { emoji: "🇦🇹", desc: "austria flag" }, { emoji: "🇦🇿", desc: "azerbaijan flag" }, { emoji: "🇧🇸", desc: "bahamas flag" }, { emoji: "🇧🇭", desc: "bahrain flag" }, { emoji: "🇧🇩", desc: "bangladesh flag" }, { emoji: "🇧🇧", desc: "barbados flag" }, { emoji: "🇧🇾", desc: "belarus flag" }, { emoji: "🇧🇪", desc: "belgium flag" }, { emoji: "🇧🇿", desc: "belize flag" }, { emoji: "🇧🇯", desc: "benin flag" }, { emoji: "🇧🇲", desc: "bermuda flag" }, { emoji: "🇧🇹", desc: "bhutan flag" }, { emoji: "🇧🇴", desc: "bolivia flag" }, { emoji: "🇧🇦", desc: "bosnia herzegovina flag" }, { emoji: "🇧🇼", desc: "botswana flag" }, { emoji: "🇧🇷", desc: "brazil flag" }, { emoji: "🇮🇴", desc: "british indian ocean territory flag" }, { emoji: "🇻🇬", desc: "british virgin islands flag" }, { emoji: "🇧🇳", desc: "brunei flag" }, { emoji: "🇧🇬", desc: "bulgaria flag" }, { emoji: "🇧🇫", desc: "burkina faso flag" }, { emoji: "🇧🇮", desc: "burundi flag" },
        { emoji: "🇰🇭", desc: "cambodia flag" }, { emoji: "🇨🇲", desc: "cameroon flag" }, { emoji: "🇨🇦", desc: "canada flag" }, { emoji: "🇮🇨", desc: "canary islands flag" }, { emoji: "🇨🇻", desc: "cape verde flag" }, { emoji: "🇧🇶", desc: "caribbean netherlands flag" }, { emoji: "🇰🇾", desc: "cayman islands flag" }, { emoji: "🇨🇫", desc: "central african republic flag" }, { emoji: "🇹🇩", desc: "chad flag" }, { emoji: "🇨🇱", desc: "chile flag" }, { emoji: "🇨🇳", desc: "china flag" }, { emoji: "🇨🇽", desc: "christmas island flag" }, { emoji: "🇨🇨", desc: "cocos islands flag" }, { emoji: "🇨🇴", desc: "colombia flag" }, { emoji: "🇰🇲", desc: "comoros flag" }, { emoji: "🇨🇬", desc: "congo brazzaville flag" }, { emoji: "🇨🇩", desc: "congo kinshasa flag" }, { emoji: "🇨🇰", desc: "cook islands flag" }, { emoji: "🇨🇷", desc: "costa rica flag" }, { emoji: "🇨🇮", desc: "cote ivoire flag" }, { emoji: "🇭🇷", desc: "croatia flag" }, { emoji: "🇨🇺", desc: "cuba flag" },
        { emoji: "🇨🇼", desc: "curacao flag" }, { emoji: "🇨🇾", desc: "cyprus flag" }, { emoji: "🇨🇿", desc: "czechia czech republic flag" }, { emoji: "🇩🇰", desc: "denmark flag" }, { emoji: "🇩🇯", desc: "djibouti flag" }, { emoji: "🇩🇲", desc: "dominica flag" }, { emoji: "🇩🇴", desc: "dominican republic flag" }, { emoji: "🇪🇨", desc: "ecuador flag" }, { emoji: "🇪🇬", desc: "egypt flag" }, { emoji: "🇸🇻", desc: "el salvador flag" }, { emoji: "🇬🇶", desc: "equatorial guinea flag" }, { emoji: "🇪🇷", desc: "eritrea flag" }, { emoji: "🇪🇪", desc: "estonia flag" }, { emoji: "🇸🇿", desc: "eswatini flag" }, { emoji: "🇪🇹", desc: "ethiopia flag" }, { emoji: "🇪🇺", desc: "european union flag" }, { emoji: "🇫🇰", desc: "falkland islands flag" }, { emoji: "🇫🇴", desc: "faroe islands flag" }, { emoji: "🇫🇯", desc: "fiji flag" }, { emoji: "🇫🇮", desc: "finland flag" }, { emoji: "🇫🇷", desc: "france flag" }, { emoji: "🇬🇫", desc: "french guiana flag" },
        { emoji: "🇵🇫", desc: "french polynesia flag" }, { emoji: "🇹🇫", desc: "french southern territories flag" }, { emoji: "🇬🇦", desc: "gabon flag" }, { emoji: "🇬🇲", desc: "gambia flag" }, { emoji: "🇬🇪", desc: "georgia flag" }, { emoji: "🇩🇪", desc: "germany flag" }, { emoji: "🇬🇭", desc: "ghana flag" }, { emoji: "🇬🇮", desc: "gibraltar flag" }, { emoji: "🇬🇷", desc: "greece flag" }, { emoji: "🇬🇱", desc: "greenland flag" }, { emoji: "🇬🇩", desc: "grenada flag" }, { emoji: "🇬🇵", desc: "guadeloupe flag" }, { emoji: "🇬🇺", desc: "guam flag" }, { emoji: "🇬🇹", desc: "guatemala flag" }, { emoji: "🇬🇬", desc: "guernsey flag" }, { emoji: "🇬🇳", desc: "guinea flag" }, { emoji: "🇬🇼", desc: "guinea bissau flag" }, { emoji: "🇬🇾", desc: "guyana flag" }, { emoji: "🇭🇹", desc: "haiti flag" }, { emoji: "🇭🇳", desc: "honduras flag" }, { emoji: "🇭🇰", desc: "hong kong flag" }, { emoji: "🇭🇺", desc: "hungary flag" },
        { emoji: "🇮🇸", desc: "iceland flag" }, { emoji: "🇮🇳", desc: "india flag" }, { emoji: "🇮🇩", desc: "indonesia flag" }, { emoji: "🇮🇷", desc: "iran flag" }, { emoji: "🇮🇶", desc: "iraq flag" }, { emoji: "🇮🇪", desc: "ireland flag" }, { emoji: "🇮🇲", desc: "isle man flag" }, { emoji: "🇮🇱", desc: "israel flag" }, { emoji: "🇮🇹", desc: "italy flag" }, { emoji: "🇯🇲", desc: "jamaica flag" }, { emoji: "🇯🇵", desc: "japan flag" }, { emoji: "🎌", desc: "crossed flags" }, { emoji: "🇯🇪", desc: "jersey flag" }, { emoji: "🇯🇴", desc: "jordan flag" }, { emoji: "🇰🇿", desc: "kazakhstan flag" }, { emoji: "🇰🇪", desc: "kenya flag" }, { emoji: "🇰🇮", desc: "kiribati flag" }, { emoji: "🇽🇰", desc: "kosovo flag" }, { emoji: "🇰🇼", desc: "kuwait flag" }, { emoji: "🇰🇬", desc: "kyrgyzstan flag" }, { emoji: "🇱🇦", desc: "laos flag" }, { emoji: "🇱🇻", desc: "latvia flag" },
        { emoji: "🇱🇧", desc: "lebanon flag" }, { emoji: "🇱🇸", desc: "lesotho flag" }, { emoji: "🇱🇷", desc: "liberia flag" }, { emoji: "🇱🇾", desc: "libya flag" }, { emoji: "🇱🇮", desc: "liechtenstein flag" }, { emoji: "🇱🇹", desc: "lithuania flag" }, { emoji: "🇱🇺", desc: "luxembourg flag" }, { emoji: "🇲🇴", desc: "macao flag" }, { emoji: "🇲🇬", desc: "madagascar flag" }, { emoji: "🇲🇼", desc: "malawi flag" }, { emoji: "🇲🇾", desc: "malaysia flag" }, { emoji: "🇲🇻", desc: "maldives flag" }, { emoji: "🇲🇱", desc: "mali flag" }, { emoji: "🇲🇹", desc: "malta flag" }, { emoji: "🇲🇭", desc: "marshall islands flag" }, { emoji: "🇲🇶", desc: "martinique flag" }, { emoji: "🇲🇷", desc: "mauritania flag" }, { emoji: "🇲🇺", desc: "mauritius flag" }, { emoji: "🇾🇹", desc: "mayotte flag" }, { emoji: "🇲🇽", desc: "mexico flag" }, { emoji: "🇫🇲", desc: "micronesia flag" }, { emoji: "🇲🇩", desc: "moldova flag" },
        { emoji: "🇲🇨", desc: "monaco flag" }, { emoji: "🇲🇳", desc: "mongolia flag" }, { emoji: "🇲🇪", desc: "montenegro flag" }, { emoji: "🇲🇸", desc: "montserrat flag" }, { emoji: "🇲🇦", desc: "morocco flag" }, { emoji: "🇲🇿", desc: "mozambique flag" }, { emoji: "🇲🇲", desc: "myanmar burma flag" }, { emoji: "🇳🇦", desc: "namibia flag" }, { emoji: "🇳🇷", desc: "nauru flag" }, { emoji: "🇳🇵", desc: "nepal flag" }, { emoji: "🇳🇱", desc: "netherlands flag" }, { emoji: "🇳🇨", desc: "new caledonia flag" }, { emoji: "🇳🇿", desc: "new zealand flag" }, { emoji: "🇳🇮", desc: "nicaragua flag" }, { emoji: "🇳🇪", desc: "niger flag" }, { emoji: "🇳🇬", desc: "nigeria flag" }, { emoji: "🇳🇺", desc: "niue flag" }, { emoji: "🇳🇫", desc: "norfolk island flag" }, { emoji: "🇰🇵", desc: "north korea flag" }, { emoji: "🇲🇰", desc: "north macedonia flag" }, { emoji: "🇲🇵", desc: "northern mariana islands flag" }, { emoji: "🇳🇴", desc: "norway flag" },
        { emoji: "🇴🇲", desc: "oman flag" }, { emoji: "🇵🇰", desc: "pakistan flag" }, { emoji: "🇵🇼", desc: "palau flag" }, { emoji: "🇵🇸", desc: "palestinian territories flag" }, { emoji: "🇵🇦", desc: "panama flag" }, { emoji: "🇵🇬", desc: "papua new guinea flag" }, { emoji: "🇵🇾", desc: "paraguay flag" }, { emoji: "🇵🇪", desc: "peru flag" }, { emoji: "🇵🇭", desc: "philippines flag" }, { emoji: "🇵🇳", desc: "pitcairn islands flag" }, { emoji: "🇵🇱", desc: "poland flag" }, { emoji: "🇵🇹", desc: "portugal flag" }, { emoji: "🇵🇷", desc: "puerto rico flag" }, { emoji: "🇶🇦", desc: "qatar flag" }, { emoji: "🇷🇪", desc: "reunion flag" }, { emoji: "🇷🇴", desc: "romania flag" }, { emoji: "🇷🇺", desc: "russia flag" }, { emoji: "🇷🇼", desc: "rwanda flag" }, { emoji: "🇼🇸", desc: "samoa flag" }, { emoji: "🇸🇲", desc: "san marino flag" }, { emoji: "🇸🇹", desc: "sao tome principe flag" }, { emoji: "🇸🇦", desc: "saudi arabia flag" },
        { emoji: "🇸🇳", desc: "senegal flag" }, { emoji: "🇷🇸", desc: "serbia flag" }, { emoji: "🇸🇨", desc: "seychelles flag" }, { emoji: "🇸🇱", desc: "sierra leone flag" }, { emoji: "🇸🇬", desc: "singapore flag" }, { emoji: "🇸🇽", desc: "sint maarten flag" }, { emoji: "🇸🇰", desc: "slovakia flag" }, { emoji: "🇸🇮", desc: "slovenia flag" }, { emoji: "🇬🇸", desc: "south georgia south sandwich islands flag" }, { emoji: "🇸🇧", desc: "solomon islands flag" }, { emoji: "🇸🇴", desc: "somalia flag" }, { emoji: "🇿🇦", desc: "south africa flag" }, { emoji: "🇰🇷", desc: "south korea flag" }, { emoji: "🇸🇸", desc: "south sudan flag" }, { emoji: "🇪🇸", desc: "spain flag" }, { emoji: "🇱🇰", desc: "sri lanka flag" }, { emoji: "🇧🇱", desc: "st barthelemy flag" }, { emoji: "🇸🇭", desc: "st helena flag" }, { emoji: "🇰🇳", desc: "st kitts nevis flag" }, { emoji: "🇱🇨", desc: "st lucia flag" }, { emoji: "🇵🇲", desc: "st pierre miquelon flag" }, { emoji: "🇻🇨", desc: "st vincent grenadines flag" },
        { emoji: "🇸🇩", desc: "sudan flag" }, { emoji: "🇸🇷", desc: "suriname flag" }, { emoji: "🇸🇪", desc: "sweden flag" }, { emoji: "🇨🇭", desc: "switzerland flag" }, { emoji: "🇸🇾", desc: "syria flag" }, { emoji: "🇹🇼", desc: "taiwan flag" }, { emoji: "🇹🇯", desc: "tajikistan flag" }, { emoji: "🇹🇿", desc: "tanzania flag" }, { emoji: "🇹🇭", desc: "thailand flag" }, { emoji: "🇹🇱", desc: "timor leste flag" }, { emoji: "🇹🇬", desc: "togo flag" }, { emoji: "🇹🇰", desc: "tokelau flag" }, { emoji: "🇹🇴", desc: "tonga flag" }, { emoji: "🇹🇹", desc: "trinidad tobago flag" }, { emoji: "🇹🇳", desc: "tunisia flag" }, { emoji: "🇹🇷", desc: "turkey flag" }, { emoji: "🇹🇲", desc: "turkmenistan flag" }, { emoji: "🇹🇨", desc: "turks caicos islands flag" }, { emoji: "🇹🇻", desc: "tuvalu flag" }, { emoji: "🇻🇮", desc: "us virgin islands flag" }, { emoji: "🇺🇬", desc: "uganda flag" }, { emoji: "🇺🇦", desc: "ukraine flag" },
        { emoji: "🇦🇪", desc: "united arab emirates uae flag" }, { emoji: "🇬🇧", desc: "united kingdom uk flag" }, { emoji: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", desc: "england flag" }, { emoji: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", desc: "scotland flag" }, { emoji: "🏴󠁧󠁢󠁷󠁬󠁳󠁿", desc: "wales flag" }, { emoji: "🇺🇸", desc: "united states usa flag" }, { emoji: "🇺🇾", desc: "uruguay flag" }, { emoji: "🇺🇿", desc: "uzbekistan flag" }, { emoji: "🇻🇺", desc: "vanuatu flag" }, { emoji: "🇻🇦", desc: "vatican city flag" }, { emoji: "🇻🇪", desc: "venezuela flag" }, { emoji: "🇻🇳", desc: "vietnam flag" }, { emoji: "🇼🇫", desc: "wallis futuna flag" }, { emoji: "🇪🇭", desc: "western sahara flag" }, { emoji: "🇾🇪", desc: "yemen flag" }, { emoji: "🇿🇲", desc: "zambia flag" }, { emoji: "🇿🇼", desc: "zimbabwe flag" }
      ],
    },
  ];

  let searchQuery = $state("");
  let copiedEmoji = $state<string | null>(null);
  let selectedCategory = $state<string | null>(null);

  let filteredCategories = $derived(() => {
    if (!searchQuery) {
      if (selectedCategory) {
        return emojiCategories.filter((c) => c.name === selectedCategory);
      }
      return emojiCategories;
    }
    
    const query = searchQuery.toLowerCase();
    return emojiCategories
      .map((category) => ({
        ...category,
        emojis: category.emojis.filter((item) => 
          item.emoji.includes(query) || item.desc.toLowerCase().includes(query)
        ),
      }))
      .filter((category) => category.emojis.length > 0);
  });

  function copyEmoji(emoji: string) {
    navigator.clipboard.writeText(emoji);
    copiedEmoji = emoji;
    setTimeout(() => {
      copiedEmoji = null;
    }, 300);
  }

  function getTotalCount() {
    return emojiCategories.reduce((sum, cat) => sum + cat.emojis.length, 0);
  }
</script>

<div class="h-full flex flex-col">
  <header class="mb-4">
    <p class="text-sm text-(--color-text-muted)">
      Browse and copy emojis. Click any emoji to copy it to clipboard. ({getTotalCount()} emojis)
    </p>
  </header>

  <!-- Search and Filter -->
  <div class="flex flex-col sm:flex-row gap-3 mb-4">
    <div class="flex-1">
      <input
        type="text"
        bind:value={searchQuery}
        placeholder="Search emojis..."
        class="w-full px-3 py-2 border border-(--color-border) bg-(--color-bg-alt) text-(--color-text) text-sm focus:outline-none focus:border-(--color-accent)"
      />
    </div>
    <div>
      <select
        bind:value={selectedCategory}
        class="w-full sm:w-auto px-3 py-2 border border-(--color-border) bg-(--color-bg-alt) text-(--color-text) text-sm focus:outline-none focus:border-(--color-accent) cursor-pointer"
      >
        <option value={null}>All Categories</option>
        {#each emojiCategories as category}
          <option value={category.name}>{category.name}</option>
        {/each}
      </select>
    </div>
  </div>

  <!-- Emoji Grid -->
  <div class="flex-1 overflow-y-auto">
    {#each filteredCategories() as category}
      <div class="mb-6">
        <h2 class="text-sm font-medium text-(--color-text-light) uppercase tracking-wider mb-3 sticky top-0 bg-(--color-bg) py-2">
          {category.name}
          <span class="text-(--color-text-muted) font-normal">({category.emojis.length})</span>
        </h2>
        <div class="grid grid-cols-4 sm:grid-cols-6 md:grid-cols-8 lg:grid-cols-10 xl:grid-cols-12 gap-0 border-l border-t border-(--color-border)">
          {#each category.emojis as item}
            <button
              onclick={() => copyEmoji(item.emoji)}
              class="flex flex-col items-center justify-center p-2 hover:bg-(--color-bg-alt) border-r border-b border-(--color-border) transition-all duration-150 cursor-pointer {copiedEmoji === item.emoji ? 'bg-(--color-accent) scale-95' : ''}"
              title={item.desc}
            >
              <span class="text-2xl">{item.emoji}</span>
              <span class="text-[10px] text-(--color-text-muted) mt-1 truncate w-full text-center leading-tight">{item.desc}</span>
            </button>
          {/each}
        </div>
      </div>
    {/each}

    {#if filteredCategories().length === 0}
      <div class="text-center py-12 text-(--color-text-muted)">
        No emojis found matching "{searchQuery}"
      </div>
    {/if}
  </div>
</div>
